<a href="https://colab.research.google.com/github/yojulab/study_AIs/blob/main/docs/NLPs/wordcloud_korean_tokenizers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 데이터 전처리

In [ ]:
it_sentences = [
    "인공지능 기술이 사회의 다양한 분야에 점점 더 널리 적용되고 있다.",
    "클라우드 컴퓨팅은 데이터 저장과 처리를 더욱 효율적으로 만들어 주며, 기업의 IT 인프라를 혁신하고 있다.",
    "머신러닝과 딥러닝 알고리즘은 데이터 분석과 예측 모델링에 혁명을 일으키고 있다.",
    # "블록체인 기술은 금융 거래의 투명성과 보안성을 향상시키는데 기여하고 있다.",
    # "사이버 보안은 디지털 시대의 중요한 이슈로 부상하고 있으며, 지속적인 관심과 개선이 요구된다.",
    # "소프트웨어 개발에서의 애자일 방법론은 빠른 시장 변화에 효과적으로 대응할 수 있게 해준다.",
    # "데이터 과학과 분석은 비즈니스 의사 결정 과정에서 중요한 역할을 하며, 기업의 경쟁력을 강화시킨다.",
    # "사물인터넷(IoT) 기술은 일상 생활을 더욱 편리하고 연결된 공간으로 변화시키고 있다.",
    # "가상현실(VR)과 증강현실(AR) 기술은 엔터테인먼트, 교육, 의료 등 다양한 분야에서 새로운 경험을 제공한다.",
    # "파이썬은 데이터 과학, 웹 개발, 자동화 스크립트 작성 등 다양한 프로그래밍 작업에 널리 사용되는 언어이다."
]

In [ ]:
!pip install python-mecab-ko

In [ ]:
from mecab import MeCab
mecab = MeCab()

In [ ]:
morphs_nouns = []
morphs_nouns_list = []
for sentence in it_sentences:
  morphs = mecab.nouns(sentence)
  morphs_nouns.append(morphs)
  morphs_nouns_list = morphs_nouns_list + morphs
  pass

# morphs_nouns
# morphs_nouns_list

In [ ]:
corpus = list(map(lambda x:' '.join(x) ,morphs_nouns))
corpus[:2]

['인공지능 기술 사회 다양 분야 적용', '클라우드 컴퓨팅 데이터 저장 처리 효율 기업 인프라 혁신']

### Tfidf Vectorizing

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidfVectorizer = TfidfVectorizer()
result_vectors = tfidfVectorizer.fit_transform(corpus)
result_vectors

<3x22 sparse matrix of type '<class 'numpy.float64'>'
	with 23 stored elements in Compressed Sparse Row format>

In [ ]:
tfidfVectorizer.vocabulary_

{'인공지능': 12,
 '기술': 0,
 '사회': 9,
 '다양': 2,
 '분야': 8,
 '적용': 15,
 '클라우드': 18,
 '컴퓨팅': 17,
 '데이터': 3,
 '저장': 14,
 '처리': 16,
 '효율': 21,
 '기업': 1,
 '인프라': 13,
 '혁신': 20,
 '머신': 5,
 '러닝': 4,
 '알고리즘': 10,
 '분석': 7,
 '예측': 11,
 '모델링': 6,
 '혁명': 19}

In [ ]:
# result_vectors.toarray()[:2]
dtm = result_vectors.toarray()
dtm.shape

(3, 22)

In [ ]:
# tfidfVectorizer.get_feature_names_out()[:2]
vocabs = tfidfVectorizer.get_feature_names_out()
len(vocabs)

22

In [ ]:
import pandas as pd
df_dtm = pd.DataFrame(dtm, columns=vocabs)
# df_dtm.T
df_dtm.values.T

array([[0.40824829, 0.        , 0.        ],
       [0.        , 0.34142622, 0.        ],
       [0.40824829, 0.        , 0.        ],
       [0.        , 0.25966344, 0.23383201],
       [0.        , 0.        , 0.61492198],
       [0.        , 0.        , 0.30746099],
       [0.        , 0.        , 0.30746099],
       [0.        , 0.        , 0.30746099],
       [0.40824829, 0.        , 0.        ],
       [0.40824829, 0.        , 0.        ],
       [0.        , 0.        , 0.30746099],
       [0.        , 0.        , 0.30746099],
       [0.40824829, 0.        , 0.        ],
       [0.        , 0.34142622, 0.        ],
       [0.        , 0.34142622, 0.        ],
       [0.40824829, 0.        , 0.        ],
       [0.        , 0.34142622, 0.        ],
       [0.        , 0.34142622, 0.        ],
       [0.        , 0.34142622, 0.        ],
       [0.        , 0.        , 0.30746099],
       [0.        , 0.34142622, 0.        ],
       [0.        , 0.34142622, 0.        ]])

In [ ]:
vocabs

array(['기술', '기업', '다양', '데이터', '러닝', '머신', '모델링', '분석', '분야', '사회',
       '알고리즘', '예측', '인공지능', '인프라', '저장', '적용', '처리', '컴퓨팅', '클라우드', '혁명',
       '혁신', '효율'], dtype=object)

In [ ]:
# tfidfVectorizer.idf_.shape
tfidfVectorizer.idf_

array([1.69314718, 1.69314718, 1.69314718, 1.28768207, 1.69314718,
       1.69314718, 1.69314718, 1.69314718, 1.69314718, 1.69314718,
       1.69314718, 1.69314718, 1.69314718, 1.69314718, 1.69314718,
       1.69314718, 1.69314718, 1.69314718, 1.69314718, 1.69314718,
       1.69314718, 1.69314718])

In [ ]:
display(df_dtm.style.background_gradient())


In [ ]:
test_text = "머신러닝과 딥러닝 알고리즘은 데이터 분석과 예측 모델링에 혁명을 일으키고 있다."
morphs_noun = mecab.nouns(test_text)
vocab = tfidfVectorizer.transform(morphs_noun)

In [ ]:
morphs_noun

['머신', '러닝', '딥', '러닝', '알고리즘', '데이터', '분석', '예측', '모델링', '혁명']

In [ ]:
vocab.toarray()

array([[0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,